name: Build Docker Image

on: 
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: set up Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Build docker image
              run: docker build -t devops-app:latest .  

            - name: Run container and test
              run: |
                    docker run -d --name test-container -p 8000:8000 devops-app:latest
                    sleep 5
                    curl -f http://localhost:8000
                    docker stop test-container
                    docker rm test-container
